### ISSUE TITLE
peer catch timeout while createing chaincode container

### ISSUE THREAD

**Issue by jiahaoc1993** [chawlanikhil24/hyperledger-fabric-k8s#4]
After creating  and joining channel, I instantiate chaincode though command below :
`peer chaincode instantiate -o orderer0.orgorderer-f-1:7050 -C mychannel -n mycc -v 1.0 -c '{"Args":["init","a","100","b","200"]}' -P "OR    ('Org1MSP.member','Org2MSP.member')" 
`

however, peer catch the timeout and fail to instantiate chaincode because the chaincode container exited for this reason:
`2017-07-25 12:11:16.539 UTC [shim] userChaincodeStreamGetter -> ERRO 001 Error trying to connect to local peer: context deadline exceeded
Error starting Simple chaincode: Error trying to connect to local peer: context deadline exceeded
` 
It seem like DNS doesn't work correctly.

**Comment by chawlanikhil24** [comment]
@LordGoodman , this is due to the env Variable, CHAINCODE_LISTEN_ADDRESS in peers. 
Do have a look in peer0.yaml and the rst of the peers.

**Comment by jiahaoc1993** [comment]
After I added some docker options at worker, the problem I have mentioned above can be fixed.
modification like this:
`DOCKER_OPTS=" --bip=172.1.86.1/24 --ip-masq=false --mtu=1472 --dns=10.0.0.10 --dns=10.117.0.1  --dns-search default.svc.cluster.local --dns-search svc.cluster.local \
               --dns-opt ndots:2 --dns-opt timeout:2 --dns-opt attempts:2 `

10.0.0.10 is an address of K8S dns  and the another one is local dns

**Comment by jiahaoc1993** [comment]
@chawlanikhil24 I'm pretty sure every CHAINCODE_LISTEN_ADDRESS was set correctly

**Comment by chawlanikhil24** [comment]
I've commented this environment variable for a while, since, it was causing problem in binding to this address.
            # - name: CORE_PEER_CHAINCODELISTENADDRESS
            #   value: "peer0-org1:7052"

Can you share your yamls on github ?

**Comment by LordGoodman** [comment]
@chawlanikhil24 sure check this out https://github.com/LordGoodman/UpdateMyself/blob/master/k8s/setupCluster/crypto-config/peerOrganizations/org1-f-1/peers/peer0.org1-f-1/peer0.org1-f-1.yaml
I set namespace to identify different orgs
